# Generated by Django 5.0.3 on 2024-03-12 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='records',
            name='terminal_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_record', to='terminal.terminalcommands'),
        ),
    ]
