# Generated by Django 4.1.13 on 2024-03-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='terminal_command',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='command_record', to='terminal.terminalcommands'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
