# Generated by Django 4.1.13 on 2024-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_remove_records_terminal_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
